services:
  backend:
    build: "./backend"
    environment:
      KEYCLOAK_BASE_URI: http://keycloak:8080
      KEYCLOAK_CLIENT_ID: user-service
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET:-J529zbiOM91EWc2kkkReqXeCjc6gkptKZyxBXQs1K4tBb7ISKkVcaVbKF5clehzaFTC38E5AT9kLk7w2m44OlW} 
      KEYCLOAK_REALM: carnode
      SEED_DATA: true
      KEYCLOAK_ISSUER: http://keycloak:8080/realms/carnode
      MONGODB_URI: mongodb://admin:admin@carnode-db:27017/?authSource=admin
      MONGODB_DATABASE: carnode
    ports:
      - "3000:3000"
    networks:
      - backend
    depends_on:
      keycloak:
        condition: service_started
      carnode-db:
        condition: service_healthy
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_HOSTNAME_PORT: 8080
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: kc_admin
      KC_DB_PASSWORD: kc_password
      KC_HOSTNAME: keycloak
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
    command: ["start-dev"]
    ports:
      - "8080:8080"
      - "9000:9000"
    networks:
      - backend
    depends_on:
      keycloak-db:
        condition: service_healthy

  keycloak-db:
    image: postgres:17
    environment:
      POSTGRES_USER: kc_admin
      POSTGRES_PASSWORD: kc_password
      POSTGRES_DB: keycloak
    ports:
      - "5433:5432"
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    restart: always
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kc_admin -d keycloak"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
  carnode-db:
    image: mongo:8
    container_name: carnode-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-admin}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-carnode}
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - carnode-mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s 
    networks:
      - backend


networks:
  backend:
  

volumes:
  keycloak_data:
  app_data:
  carnode-mongo-data:
